unit unitVueASCII;
{$codepage utf8}
{$mode objfpc}{$H+}

interface
//Affiche le logo du jeu
procedure afficherLogo();
//Dessine le logo du repos
procedure afficherSleep();
  
  
implementation
uses
  SysUtils, Classes, GestionEcran;
  
//affiche un pixel de couleur color à la position du curseur
procedure dessinerPixel(color:integer);
begin
  couleurFond(color);
  write('  ');
end;

//affiche une chaine de caractères en l'interprétant comme une succession de pixels colorés
procedure dessinerLignePixel(ligne : string);
const
   colBord = DarkGray;
   colOeil = Black;
   colCorne = Brown; 
   colNoir = Black;
   colInter = LightGray;
   colFond = Black;
   colRouge = LightRed;
   colTexte = White;
   colBUT = Brown;
var
  i:integer;
begin
  for i:= 1 to Length(ligne) do
      case ligne[i] of
           'W',' ':dessinerPixel(colFond);
           'B':dessinerPixel(colBord);
           'R':dessinerPixel(colRouge);
           'C':dessinerPixel(colCorne);
           'O':dessinerPixel(colOeil);
           'I':dessinerPixel(colInter);
           'T':dessinerPixel(colTexte);
           'U':dessinerPixel(colBUT);
      end;
  writeln;
end;

//Affiche le logo du jeu
procedure afficherLogo();
begin
  //On redimensionne la console
  changerTailleConsole(200,40);
  effacerEcran();
writeln;  
  writeln;
  dessinerLignePixel('WWWWWWWWWWWWWWWWWWWWBBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWWWWWWWBBBBIIIBBBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWBBBBWBBIIIBIIIBIIIBBWBBBBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWCCCBIIIIBIIIIIBIIIBIIIIIIBIIIBCCCWWWWWWWWWWWWUUUUWWWTTTTTWWTTTTTWWTTTTWWWWTTTTWWWWWWWW');
  dessinerLignePixel('WWWWCCCCBIIIBIIIIIIBIIIBIIIIIIBIIIBCCCCWWWWWWWWWWWUWWWUWWTWWWWWWTWWWWWWTWWWTWWTWWWWWWWWWWWW');
  dessinerLignePixel('WWWCCCCCBIIIBIIIIIIBIIIBIIIIIIBIIIBCCCCCWWWWWWWWWWUWWWUWWTWWWWWWTWWWWWWTWWWTWWTWWWWWWWWWWWW');
  dessinerLignePixel('WWCCCCCCBIIBIIIIIIIBIIIBIIIIIIIBIIBCCCCCCWWWWWWWWWUUUUWWWTTTWWWWTTTWWWWTTTTWWWWTTTWWWWWWWWW');
  dessinerLignePixel('WWCCCCCCBIIBIIIIIIIBIIIBIIIIIIIBIIBCCCCCCWWWWWWWWWUWWWUWWTWWWWWWTWWWWWWTWTWWWWWWWWTWWWWWWWW');
  dessinerLignePixel('WWCCCCCCBIIBIIIIIIIBIIIBIIIIIIIBIIBCCCCCCWWWWWWWWWUWWWUWWTWWWWWWTWWWWWWTWWTWWWWWWWTWWWWWWWW');
  dessinerLignePixel('WWCCCCCCWBBIIIIIIIIBIIIBIIIIIIIIBBWCCCCCCWWWWWWWWWUUUUWWWTTTTTWWTTTTTWWTWWWTWWTTTTWWWWWWWWW');
  dessinerLignePixel('WWCCCCCCWWBIIIIIIIIBIIIBIIIIIIIIBWWCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWCCCCCCWBIOOOOIIIIBIIIBIIIIOOOOWBWCCCCCCWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWCCCCCCWBIIIIIOOOOBIIIBOOOOIIIIIBWCCCCCCWWWWWWWWWTTTTTWWUWWWUWWTWWWTWWTWWWTWWTTTTTWWTWWWWWWWTTTT');
  dessinerLignePixel('WWCCCCCCCBIOOOOIIIIBIIIBIIIIOOOOIBCCCCCCCWWWWWWWWWWWTWWWWUWWWUWWTTWWTWWTTWWTWWTWWWWWWTWWWWWWTWWWW');
  dessinerLignePixel('WWWCCCCCCBIOOOOOOOOBIIIBOOOOOOOOIBCCCCCCWWWWWWWWWWWWTWWWWUWWWUWWTWTWTWWTWTWTWWTWWWWWWTWWWWWWTWWWW');
  dessinerLignePixel('WWWWCCCCCBIIOOOOOOOBIIIBOOOOOOOIIBCCCCCWWWWWWWWWWWWWTWWWWUWWWUWWTWTWTWWTWTWTWWTTTWWWWTWWWWWWWTTTW');
  dessinerLignePixel('WWWWWWCCCCBIIOOOOOOBIIIBOOOOOOIIBCCCCWWWWWWWWWWWWWWWTWWWWUWWWUWWTWTWTWWTWTWTWWTWWWWWWTWWWWWWWWWWT');
  dessinerLignePixel('WWWWWWWWCCBIIOOOOOOBIIIBOOOOOOIIBCCWWWWWWWWWWWWWWWWWTWWWWUWWWUWWTWWTTWWTWWTTWWTWWWWWWTWWWWWWWWWWT');
  dessinerLignePixel('WWWWWWWWWWBIIIOOOOIBIIIBOOOOIIIIBWWWWWWWWWWWWWWWWWWWTWWWWWUUUWWWTWWWTWWTWWWTWWTTTTTWWTTTTTWWTTTTW');
  dessinerLignePixel('WWWWWWWWWWWBIIIIIIIBIIIBIIIIIIIBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWWBIIIIIIBBBBBBBIIIIIIBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWWWBIIIIIBWWWWWBIIIIIBWWWWWWWWWWWWWWWWWWWTTTTWWWWTTTWWWUUUUUWWTTTTTWWTWWWWWWTTTTTWWWTTTT');
  dessinerLignePixel('WWWWWWWWWWWWBIIIIBBWWWWWBBIIIIBWWWWWWWWWWWWWWWWWWWTWWWTWWTWWWTWWWWUWWWWWWTWWWWTWWWWWWTWWWWWWTWWWW');
  dessinerLignePixel('WWWWWWWWWWWWBIIIIBWWWWWWWBIIIIBWWWWWWWWWWWWWWWWWWWTWWWTWWTWWWTWWWWUWWWWWWTWWWWTWWWWWWTWWWWWWTWWWW');
  dessinerLignePixel('WWWWWWWWWWWWWBBIIBWWWWWWWBIIBBWWWWWWWWWWWWWWWWWWWWTTTTWWWTTTTTWWWWUWWWWWWTWWWWTWWWWWWTTTWWWWWTTTW');
  dessinerLignePixel('WWWWWWWWWWWWWWWBIBWWWWWWWBIBWWWWWWWWWWWWWWWWWWWWWWTWWWTWWTWWWTWWWWUWWWWWWTWWWWTWWWWWWTWWWWWWWWWWT');
  dessinerLignePixel('WWWWWWWWWWWWWWWWBBWWWWWWWBBWWWWWWWWWWWWWWWWWWWWWWWTWWWTWWTWWWTWWWWUWWWWWWTWWWWTWWWWWWTWWWWWWWWWWT');
  dessinerLignePixel('WWWWWWWWWWWWWWWWWBWWWWWWWBWWWWWWWWWWWWWWWWWWWWWWWWTTTTWWWTWWWTWWWWUWWWWWWTWWWWTTTTTWWTTTTTWWTTTTW');
  dessinerLignePixel('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
end;


//Dessine le logo du repos
procedure afficherSleep();
begin
     deplacerCurseurXY(50,5); dessinerLignePixel('TTTTTTTTTTT');
     deplacerCurseurXY(50,6); dessinerLignePixel('         T ');
     deplacerCurseurXY(50,7); dessinerLignePixel('        T  ');
     deplacerCurseurXY(50,8); dessinerLignePixel('       T   ');
     deplacerCurseurXY(50,9);dessinerLignePixel('      T    ');
     deplacerCurseurXY(50,10);dessinerLignePixel('     T     ');
     deplacerCurseurXY(50,11);dessinerLignePixel('    T              TTTTTTTTT');
     deplacerCurseurXY(50,12);dessinerLignePixel('   T                      T ');
     deplacerCurseurXY(50,13);dessinerLignePixel('  T                      T  ');
     deplacerCurseurXY(50,14);dessinerLignePixel(' T                      T   ');
     deplacerCurseurXY(50,15);dessinerLignePixel('TTTTTTTTTT             T    ');
     deplacerCurseurXY(50,16);dessinerLignePixel('                      T     ');
     deplacerCurseurXY(50,17);dessinerLignePixel('                     T      ');
     deplacerCurseurXY(50,18);dessinerLignePixel('                    T       ');
     deplacerCurseurXY(50,19);dessinerLignePixel('                   TTTTTTTTT');

     deplacerCurseurXY(50,21);dessinerLignePixel('        TTTTTTT');
     deplacerCurseurXY(50,22);dessinerLignePixel('             T ');
     deplacerCurseurXY(50,23);dessinerLignePixel('            T  ');
     deplacerCurseurXY(50,24);dessinerLignePixel('           T   ');
     deplacerCurseurXY(50,25);dessinerLignePixel('          T    ');
     deplacerCurseurXY(50,26);dessinerLignePixel('         T     ');
     deplacerCurseurXY(50,27);dessinerLignePixel('        TTTTTTT');
end;      
end.